database:
  host: ${HOST}
  port: ${POSTGRES_PORT}
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  name: "go"
  ssl_mode: "disable"
  migrations_path: "./internal/storage/pgstorage/migrations"

kafka:
  host: ${HOST}
  port: ${KAFKA_PORT}
  

redis:
  host: ${HOST}
  port: ${REDIS_PORT}


web:
  host: ${HOST}
  port: ${WEB_PORT}