database:
  host: localhost
  port: 5432
  username: postgres
  password: rootpassword
  name: postgres
  ssl_mode: "disable"

kafka:
  host: localhost
  port: 9092
  message_create_topic_name: message_create_topic_name
  route_create_topic_name: route_create_topic_name

redis:
  host: localhost
  port: 6379


web:
  host: localhost
  port: 8080

vk:
  group_id: 234823684
  admin_id: 205630058
  welcome_text: Hello and welocme
  timeout: 30s
  delay: 400ms