database:
  host: localhost
  port: 5432
  username: postgres
  password: rootpassword
  name: "go"
  ssl_mode: "disable"
  # migrations_path: "./internal/storage/pgstorage/migrations"

kafka:
  host: localhost
  port: 9092
  message_create_topic_name: message_create_topic_name

redis:
  host: localhost
  port: 6379


web:
  host: localhost
  port: 8080